import type { Metadata } from "next";
import "./globals.css";
import TopNavigation from "@/components/top-nav";
import localFont from "next/font/local";
import { SWRProvider } from "./providers/swr-provider";

// 추가: NanumSquare 로컬 폰트 (Regular, Bold)
const nanum = localFont({
  variable: "--font-nanum",
  src: [
    {
      path: "../public/fonts/NanumSquareR.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NanumSquareB.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nanum.variable} antialiased bg-gray-50`}>
        <SWRProvider>
          <TopNavigation />
          <div className="max-w-[1200px] mx-auto min-h-[calc(100vh-60px)]">
            {children}
          </div>
        </SWRProvider>
      </body>
    </html>
  );
}
